### ISSUE TITLE
Change SetCustomProperty so it doesn't delete and re-add properties, but changes its value

### ISSUE THREAD

**Issue by brinkdinges** [CAD-Booster/solidworks-api#14]
Unless there is a good reason this was done?

**Comment by brinkdinges** [comment]
We should also add a Delete method

**Comment by brinkdinges** [comment]
Added deleting with 480adab39871dbb62b545ec1dc86c6d29a6b9d45

**Comment by dhozen** [comment]
There was a bug in some previous swx versions where the change didn't work, so that's probably why it was written like that. I had to use the delete and re-add as a workaround for awhile.

**Comment by brinkdinges** [comment]
That's good to know, thanks! Any idea in which version that was, or roughly? I'd like to set a limit in SolidDna so we know which version year we can use APIs from, so if that bug was older, we can ignore it.

The other reason for it could be that two custom properties have different types. That could make updating harder.

**Comment by dhozen** [comment]
Not really sure at all, but I would say over 5 years ago? It was one of those situations where I found it wasn’t working and changed to delete/add, and then, a few years later thought “I wonder if they’ve fixed that”, and they had.The bug didn’t have to do with mixing the types since I only use text.Thanks for all your work with this—its really a big help.-Jason S.﻿
That's good to know, thanks! Any idea in which version that was, or roughly? I'd like to set a limit in SolidDna so we know which version year we can use APIs from, so if that bug was older, we can ignore it.
The other reason for it could be that two custom properties have different types. That could make updating harder.

**Comment by brinkdinges** [comment]
Changed the behavior from delete+add to update existing value with e7f87f8232a737cecae67b8be6f585aa39802431
