### ISSUE TITLE
Remove toolbars on shutdown

### ISSUE THREAD

**Issue by KC-MarKamp** [CAD-Booster/solidworks-api#34]
We do not continuously remove toolbars when closing down. My Solidworks installations are filled with toolbars from software I developed a while ago, including instances where multiple toolbars with the same name exist.

We are calling RemoveCommandGroup2 to remove the groups in CommandManager.Dispose. Do we need to remember to dispose of something that leaves a trace? Maybe RemoveCommandTab?

Note: Not deleting the toolbars on shutdown enables customization by the user but creates inconsistent behavior on the developer side.

**Comment by brinkdinges** [comment]
From making registry snapshots and trying a whole lot of toolbars, it seems like the toolbars are just never completely removed from the registry. All buttons are removed when you shut down properly, but the toolbar itself is not.

**Comment by brinkdinges** [comment]
SolidWorks API Support said toolbars are by default not written to the registry. This only happens when you set IgnorePreviousVersion to false. We set it to true by default, which seems good. 

They haven't answered my question about why I still have 20 old tabs in my command manager. Where do those come from, if not from the registry?

**Comment by brinkdinges** [comment]
API Support also doesn't know why tabs keep existing. So I guess we're not going to fix that.
